repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer
      exclude: '^LICENSE$'
    - id: check-yaml
    - id: check-added-large-files

- repo: meta
  hooks:
    - id: check-useless-excludes

- repo: https://codeberg.org/vifon/pre-commit-hooks
  rev: b4de7f6db54e5e1f893ec1138ad63c9623b0c8f3
  hooks:
    - id: shellcheck
    - id: elisp-check-parens
    - id: elisp-checkdoc
    - id: no-elc
    - id: no-tabs
